[platformio]
default_envs = t5-pro

[env:t5-pro]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=0
    -DESP32
    -DLORA_FREQ=917.375
    -DLORA_BW=62.5
    -DLORA_SF=8
    -DLORA_CR=5
    -DLORA_TX_POWER=22
    -DP_LORA_NSS=46
    -DP_LORA_DIO_1=10
    -DP_LORA_RESET=1
    -DP_LORA_BUSY=47
    -DRADIOLIB_STATIC_ONLY=1
    -DRADIOLIB_GODMODE=1
    -Isrc/board
lib_ldf_mode = deep+
lib_deps =
    adafruit/Adafruit BusIO
    file://lib/MeshCore/lib/ed25519
